# GitHub Actions, intégré directement dans GitHub, offre une plateforme puissante et flexible pour la mise en place de pipelines CI/CD.
# GitHub Actions a été lancé en 2018 ; 
# Workflow 
# job
# steps 
# checkout 
# secrets 
# environnements 
# marketplace github actions 
# Créez le répertoire .github/workflows , Créez un fichier de workflow : build.yml par exemple ; 

name: Mon Workflow # le nom de notre workflow 
on: # le déclencheur 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: # suite d'actions ou commandes à exécuter 
      - name: Checkout du code # nom de l'étape 
        uses: actions/checkout@v2 # action à utiliser ; 
      - name: Installation des dépendances
        run: npm install
      - name: Exécution des tests
        run: npm test

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Installation des dépendances
        run: npm install
      - name: Exécution des tests
        run: npm test
      - name: Archive des résultats de tests
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Téléchargement des résultats de tests
        uses: actions/download-artifact@v2
        with:
          name: test-results
      - name: Déploiement sur le serveur de production
        run: |
          # Script de déploiement ici
          echo "Déploiement de l'application sur le serveur de production."

# Les matrices vous permettent d'exécuter en parallèle un même job avec plusieurs configurations différentes. 
